name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        
    - name: Train model
      env:
        CUDA_VISIBLE_DEVICES: ""
      run: |
        python train.py
        
    - name: Run tests
      env:
        CUDA_VISIBLE_DEVICES: ""
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}"
        python -m pytest tests/
        
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 5